[package]
name = "nl_foundations"
version = "0.1.0"
authors = ["Tommy M. McGuire <mcguire@crsr.net>"]

[lib]
name = "nl_foundations"
path = "src/lib.rs"
test = true

[dependencies]
libc = "0.2.5"
getopts = "0.2"
